spring.application.name=aquastore-backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/aquastore
spring.datasource.username=postgres
spring.datasource.password=P@1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080